branch-defaults:
  default:
    environment: shacl-dashboard-app
    group_suffix: null
  main:
    environment: shacl-dashboard-app
global:
  application_name: eb-shacl-app
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: Docker
  platform_version: latest
  profile: default
  repository: null
  sc: git
  workspace_type: Application
